name: go-backend-ci
run-name: CI for go-backend project
on:
  push:
    branches:
      - 'main'

jobs:
  go-backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@f095bcc56b7c2baf48f3ac70d6d6782f4f553222

      - name: Set up go
        uses: actions/setup-go@49bc3307c5d359429e8aee983859eb8dfad28c6b
        with:
          go-version: '^1.20.3'

      # Install gotestfmt on the VM running the action.
      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@ed11bda1c41019f0864315b0194ec6d33b696492
        with:
          # Optional: pass GITHUB_TOKEN to avoid rate limiting.
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: |
          set -euo pipefail
          go test -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

      # Upload the original go test log as an artifact for later review.
      - name: Upload test log
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error
